<Project>
	<Target Name="BuildContent" BeforeTargets="BeforeCompile">
		<PropertyGroup>
			<_RawContentOutput>$(ProjectDir)$(OutputPath)</_RawContentOutput>
			<_RawContentTemp>$(ProjectDir)$(IntermediateOutputPath)</_RawContentTemp>
			<ContentOutput>$(_RawContentOutput.TrimEnd('\').TrimEnd('/'))</ContentOutput>
			<ContentTemp>$(_RawContentTemp.TrimEnd('\').TrimEnd('/'))</ContentTemp>
			<ContentArgs>build -p $(MonoGamePlatform) -s VikingBuilder/Assets -o &quot;$(ContentOutput)&quot; -i &quot;$(ContentTemp)&quot;</ContentArgs>
			<ContentCommand>$(MSBuildThisFileDirectory)bin\$(Configuration)\VikingBuilder</ContentCommand>
		</PropertyGroup>

		<MSBuild Projects="$(MSBuildThisFileDirectory)VikingBuilder.csproj"
				 Targets="Restore;Build"
				 Properties="RuntimeIdentifier=;SelfContained=false"
				 RemoveProperties="TargetFramework;RuntimeIdentifiers;Platform" />

		<Exec Command="&quot;$(ContentCommand)&quot; $(ContentArgs)" WorkingDirectory="$(MSBuildThisFileDirectory)..\" CustomErrorRegularExpression="\[E\] .+" CustomWarningRegularExpression="\[W\] .+" />
	</Target>

	<Target Name="AddGeneratedContentAssets"
	  AfterTargets="BuildContent"
	  BeforeTargets="AssignTargetPaths">
		<ItemGroup>
			<GeneratedAsset Include="$(ProjectDir)$(OutputPath)Content\**\*" />

			<AndroidAsset Include="@(GeneratedAsset)"
			  Condition="'$(MonoGamePlatform)' == 'Android'">
				<Link>Content\%(GeneratedAsset.RecursiveDir)%(GeneratedAsset.Filename)%(GeneratedAsset.Extension)</Link>
			</AndroidAsset>

			<BundledResource Include="@(GeneratedAsset)"
			  Condition="'$(MonoGamePlatform)' == 'MacOSX' Or '$(MonoGamePlatform)' == 'iOS'">
				<Link>Content\%(GeneratedAsset.RecursiveDir)%(GeneratedAsset.Filename)%(GeneratedAsset.Extension)</Link>
			</BundledResource>

			<Content Include="@(GeneratedAsset)"
			  Condition="'$(MonoGamePlatform)' == 'DesktopGL' Or '$(MonoGamePlatform)' == 'Windows'">
				<TargetPath>Content\%(GeneratedAsset.RecursiveDir)%(GeneratedAsset.Filename)%(GeneratedAsset.Extension)</TargetPath>
				<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
				<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
			</Content>
		</ItemGroup>
	</Target>
</Project>