using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VikingEngine
{
    enum SpriteName : short
    {
        NO_IMAGE = 0,

        WhiteArea,
        WhiteArea_LFtiles,
        //WarsWaterTexture,
        WhiteCirkle,
        BlockTexture,
        MissingImage,
        InterfaceBorder,
        RedErrorCross,
        
        InterfaceTextInput,
        InterfaceIconCamera,

        Keyboard,
        Mouse,
        MouseButtonLeft,
        MouseButtonDoubbleLeft,
        MouseButtonMiddle,
        MouseButtonRight,
        MouseButtonX1,
        MouseButtonX2,
        MouseAllDir,
        MouseLR,
        MouseUD,
        MouseScroll,
        ControllerVibration,

        KeyA,
        KeyB,
        KeyC,
        KeyD,
        KeyE,
        KeyF,
        KeyG,
        KeyH,
        KeyI,
        KeyJ,
        KeyK,
        KeyL,
        KeyM,
        KeyN,
        KeyO,
        KeyP,
        KeyQ,
        KeyR,
        KeyS,
        KeyT,
        KeyU,
        KeyV,
        KeyW,
        KeyX,
        KeyY,
        KeyZ,
        Key1,
        Key2,
        Key3,
        Key4,
        Key5,
        Key6,
        Key7,
        Key8,
        Key9,
        Key0,
        KeyCtrl,
        KeyAlt,
        KeyEsc,
        KeyF1,
        KeyF2,
        KeyF3,
        KeyF4,
        KeyF5,
        KeyF6,
        KeyF7,
        KeyF8,
        KeyF9,
        KeyF10,
        KeyF11,
        KeyF12,
        KeyShift,
        KeyArrowUp,
        KeyArrowDown,
        KeyArrowRight,
        KeyArrowLeft,
        KeyEnter,
        KeyTab,
        KeyBack,
        KeySpace,

        KeyPlus,
        KeyStar,
        KeyQuestionmark,
        KeySlash,
        KeyBackslash,
        KeyPeriod,
        KeyComma,
        KeyMinus,
        KeyTilde,
        KeyOpenBracket,
        KeyCloseBracket,
        KeyUnknown,
        KeyCapsLock,
        KeyPgUp,
        KeyPgDown,
        KeyEnd,
        KeyHome,
        KeyInsert,
        KeyPipe,
        KeyPrintScreen,
        KeyDelete,
        KeyQuote,
        KeySemiColon,
        ArrowKeys,

        ButtonA,
        ButtonB,
        ButtonX,
        ButtonY,
        ButtonLB,
        ButtonRB,
        ButtonLT,
        ButtonRT,
        LeftStick,
        RightStick,
        LeftStick_LR,
        LeftStick_UD,
        RightStick_LR,
        RightStick_UD,
        Dpad,
        DpadUp,
        DpadDown,
        DpadUpDown,
        DpadLeftRight,
        LSClick,
        RSClick,
        DpadLeft,
        DpadRight,
        ButtonSTART,
        ButtonBACK,

        ButtonVIEW,
        ButtonMENU,
        
        ButtonLG,
        ButtonRG,
        TouchSurface1,
        TouchSurface2,
        TouchSurface1UpDown,
        TouchSurface2UpDown,
        TouchSurface1LeftRight,
        TouchSurface2LeftRight,
        ControllerIconP1,
        ControllerIconP2,
        ControllerIconP3,
        ControllerIconP4,

        PixController1,
        PixController2,
        PixController3,
        PixController4,
        PixController5,
        PixController6,

        DisconnectSquare,

        GyroMove,
        GyroPitch,
        GyroYaw,
        GyroRoll,

        GenericButton0,
        GenericButton1,
        GenericButton2,
        GenericButton3,
        GenericButton4,
        GenericButton5,
        GenericButton6,
        GenericButton7,
        GenericButton8,
        GenericButton9,
        GenericButton10,
        GenericButton11,
        GenericButton12,
        GenericButton13,
        GenericButton14,
        GenericButtonAny,

        PsButtonTriangle,
        PsButtonCirkle,
        PsButtonSquare,
        PsButtonCross,
        PsTouchPad,
        PsButtonShare,
        PsButtonOptions,
        PsGuideButton,

        ButtonDisabledCross,
        TextureWaterMap,
        TextureHueSaturation,
        TextureDarknessGradient,
        ColorPickerCircle,

        LangButton_English,
        LangButton_Russian,
        LangButton_Spanish,
        LangButton_Portuguese,
        LangButton_German,
        LangButton_Japanese,
        LangButton_Frensh,
        LangButton_Chinese,


        IconBuildArrow,
        IconBuildSelection,
        IconBuildAdd,
        IconBuildRemove,
        IconBuildMoveSelection,
        IconBuildStamp,
        VoxelEditorIcon,

        IconColorPick,
        EditorMouseToolsIcon,
        EditorToolRoad,
        EditorToolCube,
        EditorToolPyramid,
        EditorToolCone,
        EditorToolWedge,
        EditorToolCylinder,
        EditorToolSphere,
        EditorToolPencil,
        EditorToolReColorPencil,


        IconSandGlass,
        LfClosedLock,
        EditorForwardArrow,
        
        IconApperanceHat,
        IconApperanceShirt,
        IconApperanceBeard,
        IconApperanceHair,
        IconApperanceEyes,
        IconApperanceMouth,
        IconApperanceBelt,
        FatArrow16pix,
        FatArrow16pix_Triangle,

        CreditsProgrammerArt,
        CreditsMusic,
        CreditsPlaytest,
        CreditsTranslation,

        LFEdge,  
       
        LfMountIcon,
        LFHudShield,
        LFHudHeart,
        LFHudMountHeart,
        LFHudHeartEmpty,
        LFHudCoins,
        LFHudAmmo,
        LFHudAmmoGray,
        LFHudAmmoEmpty,
        LFHudKey,
        LFHudKeyEmpty,
        LFSaveIcon,
        LFPrimaryAttackHudBG,
        LFSecondaryAttackHudBG,
        LFItemHudBG,
        LFAppleItemIcon,
        LFBasicSuitIcon1,
        LFBasicSuitIcon2,
        LFSwordsmanIcon1,
        LfMountHorseIcon,
        LfBarrelIcon,
        LFNum0,
        LFNum1,
        LFNum2,
        LFNum3,
        LFNum4,
        LFNum5,
        LFNum6,
        LFNum7,
        LFNum8,
        LFNum9,
        LFNumPlus,
        LFNumMinus,
        LFNumStar,
        LFSwordsmanIcon2,
        LFDaneIcon1,
        LFDaneIcon2,
        LFDualIcon1,
        LFDualIcon2,
        LFSpearmanIcon1,
        LFSpearmanIcon2,
        LFArcherIcon2,
        LfShapeshifterIcon1,
        LfShapeshifterIcon2,
        LfWolfShieldHead,
        LfLifeIcon,
        LFLevelCompleteIcon,
        LFLevelUnCompleteIcon,
        LfFinalLevelCompleteIcon,
        LfFinalLevelUnCompleteIcon,
        LfChallengeLevelCompleteIcon,
        LfChallengeLevelUnCompleteIcon,

        LFTutorialLevelIcon,
        LFLobbyIcon,
        LFLevelIcon,
        LfFinalLevelIcon,
        LfChallengeLevelIcon,
        
        LFApplePieItemIcon,
        LfCardItemIcon,
        LFNewSaveFileIcon,
        LfGunMashine,
        LfGunSideArm,
        LfHandgranade,
        LfPickAxe,
        LfNpcSpeechArrow,
        LfEmoIcon2,
        LfOpenLock,
        LfMithrilIngot,
        LfEmoIcon1,
        LfNpcCraftArrow,
        LfWeaponSmithHead1,
        LfWeaponSmithHead2,
        LfCraftItemIcon,
        LfSadTrollFace,
        LfGranpaHead1,
        LfGranpaHead2,
        LfVeteranHead1, LfVeteranHead2,
        LfFatherHead1, LfFatherHead2,
        LfTutPrimaryAttack,
        LfTutBrokenTarget,
        LfTutSpecialAttack,
        LfTutJump,
        LfBabyIcon,
        LfCheckpointFlag,
        LfTransportIcon,
        LfBabyProgressIcon,
       
        LFMenuRectangleSelection,
        
        //LFMenuLootMessage,
        LfMenuMoreMenusArrow,
        LfCheckYes,
        LfCheckNo,
        LfChatBobbleIcon,
        LfClientCompassArrow,



        LFMessageBackground,
        EditorMultiSelection,
        EditorRemoveCross,
        EditorEmptyBlockFrame,

        EditorPencilCube,
        EditorPencilShadow,
        EditorPencilShadow1,
        EditorPencilShadow2,
        EditorPencilShadow3,
        EditorPencilShadow4,
        EditorPencilShadow5,
        EditorPencilShadow6,
        EditorFillAreaTexture,
        
        LFMenuPointer,

        LFAppearHairCol,
        LFAppearEyes,
        LFAppearMouth,
        LFAppearBeardCol,
        LFAppearBeard,
        LFAppearSkinCol,
        LFAppearClothCol,
        LFAppearPantsCol,
        LFAppearShoeCol,
        LFAppearBeltCol,
        LFAppearBeltDetailCol,
        LFAppearHatMainCol,
        LFAppearHatDetailCol,
        LFAppearHat,

        LFAppearHatTypeCap,
        LFAppearHatTypeWitch,
        LFAppearHatTypeFootball,
        LFAppearHatTypePirate1,
        LFAppearHatTypePirate2,
        LFAppearHatTypePirate3,
        LFAppearHatTypeSanta1,
        LFAppearHatTypeSanta2,
        LFAppearHatTypeSanta3,
        LFAppearHatTypeBaby1,
        LFAppearHatTypeBaby2,

        LFAppearHatTypeArrow, 
        LFAppearHatTypeBucket, 
        LFAppearHatTypeCoif1, 
        LFAppearHatTypeCoif2, 
        LFAppearHatTypeHigh1, 
        LFAppearHatTypeHigh2,
        LFAppearHatTypeHunter1, 
        LFAppearHatTypeHunter2, 
        LFAppearHatTypeHunter3,
        LFAppearHatTypeLow1, 
        LFAppearHatTypeLow2, 
        LFAppearHatTypeMini1, 
        LFAppearHatTypeMini2, 
        LFAppearHatTypeMini3,
        LFAppearHatTypeTurban1, 
        LFAppearHatTypeTurban2,
        LFAppearHatTypeHeadband1, 
        LFAppearHatTypeHeadband2, 
        LFAppearHatTypeHeadband3,
        LFAppearHatTypecrown1, 
        LFAppearHatTypecrown2, 
        LFAppearHatTypecrown3, 
        LFAppearHatTypeprincess1, 
        LFAppearHatTypeprincess2,
        LFAppearHatTypeMaskTurtle1, 
        LFAppearHatTypeMaskZorro1, 
        LFAppearHatTypeMaskZorro2, 
        LFAppearHatTypeZelda,

        LFAppearHairTypeNormal,
        LFAppearHairTypeSpiky1,
        LFAppearHairTypeSpiky2,
        LFAppearHairTypeRag1,
        LFAppearHairTypeRag2,
        LFAppearHairTypeBald1,
        LFAppearHairTypeBald2,
        LFAppearHairTypeGirlyShort1,
        LFAppearHairTypeGirlyShort2,
        LFAppearHairTypeGirlyLong1,
        LFAppearHairTypeGirlyLong2,
        LFAppearHairTypeEmo1,
        LFAppearHairTypeEmo2,
        LFAppearHairTypeEmo3,

        LFAppearMouthTypeNoMouth,
        LFAppearMouthTypeSmile,
        LFAppearMouthTypeBigSmile,
        LFAppearMouthTypeSideSmile1,
        LFAppearMouthTypeSideSmile2,
        LFAppearMouthTypeWideSmile,
        LFAppearMouthTypeopen_smile,
        LFAppearMouthTypeLoony,
        LFAppearMouthTypeStraight,
        LFAppearMouthTypeteeth1,
        LFAppearMouthTypeteeth2,
        LFAppearMouthTypeteeth3,
        LFAppearMouthTypeOMG,
        LFAppearMouthTypeHmm,
        LFAppearMouthTypeSour,
        LFAppearMouthTypesouropen,
        LFAppearMouthTypeOrc,
        LFAppearMouthTypevampire,
        LFAppearMouthTypeGasp,
        LFAppearMouthTypeLaugh,
        LFAppearMouthTypeGirly1,
        LFAppearMouthTypeGirly2,
        LFAppearMouthTypePirate,
        LFAppearMouthTypeBaby1,
        LFAppearMouthTypeBaby2,

        LFAppearEyeTypeNoEyes,
        LFAppearEyeTypeNormal,
        LFAppearEyeTypeSunshine,
        LFAppearEyeTypeWink,
        LFAppearEyeTypeLoony,
        LFAppearEyeTypeSlim,
        LFAppearEyeTypeFrown,
        LFAppearEyeTypeHardShut,
        LFAppearEyeTypeEvil,
        LFAppearEyeTypeRed,
        LFAppearEyeTypeSleepy,
        LFAppearEyeTypeSleepyCross,
        LFAppearEyeTypeCross,
        LFAppearEyeTypeCrossed1, LFAppearEyeTypeCrossed2, LFAppearEyeTypeCrossed3, LFAppearEyeTypeCrossed4, LFAppearEyeTypeCrossed5,
        LFAppearEyeTypeSad1, LFAppearEyeTypeSad2, LFAppearEyeTypeSad3, LFAppearEyeTypeSad4, LFAppearEyeTypeSad5, 
        LFAppearEyeTypeCyclops,
        LFAppearEyeTypeVertical,
        LFAppearEyeTypeGirly1, LFAppearEyeTypeGirly2, LFAppearEyeTypeGirly3, 
        LFAppearEyeTypePirate,
        LFAppearEyeTypeSunGlasses1,
        LFAppearEyeTypeSunGlasses2,
        LFAppearEyeTypeEmo1,
        LFAppearEyeTypeEmo2,

        LFExpressLoot,
        LFExpressSad,
        LFExpressAngry,
        LFExpressTease,
        LFExpressThumbsUp,
        LFExpressHi,
        LFExpressLaugh,
        LFExpressDuck,


        LfAchievementFinalBoss,
        LfAchievementAllLevels,
        LfAchievementAllCards,
        LfAchievementFinalBoss_lock,
        LfAchievementAllLevels_lock,
        LfAchievementAllCards_lock,
        
        LFMaterialStart,
        LFMaterialEnd, //= LFMaterialStart + Byte.MaxValue,
        
        #region LF2
        LFIconMap,
        LFIconDiscardItem,
        IconMapFlag,
        TrophySword,
        IconTown,
        IconMenuCloseGame,
        IconMapQuest,
        IconBackpack,
        IconQuestLog,
        BoardIconChat,
        LFIconLetter,
        LFIconMirror,
        IconMenuMultiplayer,
        IconMenuSettings,
        //TrophyUnlocked,
        BoardIconRules,

        IconLaugh,
        IconSour,
        IconTeasing,
        IconThumbUp,
        IconHand,

        TrophyUnlocked,
        BoardIconDelete,
        IconBossKey,
        #endregion

        #region Goods
        GoodsGlass,
        GoodsGlassBroken,
        GoodsGemRed,
        GoodsGemChrystal,
        GoodsGemDiamond,
        GoodsGemBlack,
        GoodsScroll,
        GoodsApple,
        GoodsAppleGrilled,
        GoodsWine,
        GoodsBread,
        GoodsSeed,
        GoodsGrapes,
        GoodsTusk,
        GoodsTeeth,
        GoodsHorn,
        GoodsNoseHorn,
        GoodsLeather,
        GoodsSkinn,
        GoodsLeatherScaled,
        GoodsFur,
        GoodsFeather,
        GoodsMeat,
        GoodsGrilledMeat,
        GoodsSlingstone,
        GoodsStoneGranit,
        GoodsStoneMarmour,
        GoodsStoneSand,
        GoodsStoneFlint,
        GoodsMetalIron,
        GoodsMetalBronze,
        GoodsMetalSilver,
        GoodsMetalGold,
        GoodsMetalMithril,
        GoodsStick,
        GoodsWood,
        GoodsBloodFingerHerb,
        GoodsFrogHeartHerb,
        GoodsFireStarHerb,
        GoodsBlueRoseHerb,

        GoodsBlackTooth,
        GoodsBladderStone,
        GoodsRib,
        GoodsPlastma,
        GoodsThread,
        GoodsCoal,
        GoodsInk,
        GoodsPoisionSting,
        GoodsHonny,
        GoodsVax,
        GoodsBlackEye,
        GoodsPaw,
        GoodsHolyWater,

        ItemGreenBottle,
        ItemBlueBottle,
        ItemRedBottle,
        ItemYellowBottle,
        ItemPurpleBottle,
        ItemGoldenBomb,
        ItemGoldenArrow,

        ItemCookie,
        ItemGoldenCookie,
        ItemCandle,
        ItemBeer,
        ItemOrcMead,
        ItemLuckyPaw,
        ItemCoinOrc,
        ItemCoinDwarf,
        ItemCoinSouth,
        ItemCoinElf,
        ItemCoinAncient,
        ItemCoinNordic,
        ItemWaterFull,
        ItemWaterEmpty,
        ItemRepairKit,

        #endregion

        #region LF_Items
        WeaponDaggerIron,
        WeaponDaggerSilver,
        WeaponDaggerMithril,
        WeaponDaggerBronze,
        WeaponDaggerGold,

        WeaponSwordWood,
        WeaponSwordIron,
        WeaponSwordSilver,
        WeaponSwordMithril,
        WeaponSwordBronze,
        WeaponSwordGold,
        WeaponLongSwordBronze,
        WeaponLongSwordIron,
        WeaponLongSwordSilver,
        WeaponLongSwordGold,
        WeaponLongSwordMithril,
        WeaponPickAxe,
        WeaponSickle,
        WeaponBuildHammer,

        WeaponAxeBronze,
        WeaponAxeIron,
        WeaponAxeSilver,
        WeaponAxeGold,
        WeaponAxeMithril,

        WeaponDaneAxeBronze,
        WeaponDaneAxeIron,
        WeaponDaneAxeSilver,
        WeaponDaneAxeGold,
        WeaponDaneAxeMithril,

        WeaponSlingshot,
        WeaponShortBow,
        WeaponLongBow,
        WeaponSpecialBow,

        WeaponStaff,
        WeaponHandSpear,
        WeaponStick,

        ArmourSkin,
        ArmourIron,
        ArmourMithril,
        ArmourBronze,
        ArmourLeather,
        ArmourSilver,
        ArmourGold,
        ArmourScaled,

        ShieldBuckle,
        ShieldRound,
        ShieldSquare,


        HelmetBronze,
        HelmetLeather,
        HelmetIron,
        HelmetMithril,
        HelmetGold,



        RingBasic,
        RingRed,
        RingBlue,
        RingWhite,
        RingBlack,
        RingGreen,

        #endregion

        FlipHori,
        FlipVerti,
        RotateCCW,
        RotateCW,
        CamZoom,
        CamAngleY,
        CamAngleX,
        CamPersonMode,
        CamPan,
        Xdir,
        Ydir,
        Zdir,
        width,
        height,
        length,
        PrevFrame,
        NextFrame,
        Undo,
        

        #region Commander

        cmd0,
        cmd1,
        cmd2,
        cmd3,
        cmd4,
        cmd5,
        cmd6,
        cmd7,
        cmd8,
        cmd9,
        cmdDiv,
        cmdPlus,
        cmdMinus,
        cmdExclamation,
        cmdBrokenHeart,

        cmdTileMountain_Old,
        cmdTileGrass1,
        cmdTileGrass2,
        cmdTileGrass3,
        cmdTileGrass4,
        cmdTileGrassB1,
        cmdTileGrassB2,
        cmdTileGrassB3,
        cmdTileGrassBTree,
        cmdTileGrassBRock,
        cmdTileGrassBTreeModel,
        cmdTileGrassBRockModel,
        cmdTileGrassBMud1,
        cmdTileGrassBMud2,

        cmdTileForest,
        cmdTileWater,
        cmdTileHill,
        cmdTileTown,
        cmdTileEmpty,
        cmdTileRubble,
        cmdTileSwamp,
        cmdTileMountain,
        cmdTileStoneWall,
        cmdTileStoneGate,
        cmdTileEdgeGrass,
        cmdTileOpenWater,
        cmdTileCastle,
        cmdTilePalisad,
        cmdTilePavedRoad,

        cmdTileDungeonGround,
        cmdTileDungeonWall,
        cmdTileMountainwallFloorEdge1,
        cmdTileMountainwallFloorEdge2,
        cmdTileMountainwallFloorEdge3,
        cmdTileMountainwallTop,
        cmdTileMountainwall1,
        cmdTileMountainwall2,
        cmdTileMountainwall3,

        cmdTileHouseTop,
        cmdTileHouseWall1,
        cmdTileHouseWall2,
        cmdTileHouseWall3,
        cmdTileHouseGround1,
        cmdTileHouseGround2,
        cmdTileHouseGround3,
        cmdTileHouseGround4,

        cmdTileMountBrickWallTop,
        cmdTileMountBrickWall,
        cmdTileMountBrickWallTorch,
        cmdTileMountBrickWallTorchSprite,

        cmdTileMountainGroundStone1,
        cmdTileMountainGroundStone2,
        cmdTileMountainGroundStone3,
        cmdTileMountainGroundStone4,
        cmdTileMountainGroundStone5,

        cmdTileGroundEdgeGrass1,
        cmdTileWallIvy1,

        cmdTileMountainGround1,
        cmdTileMountainGround2,
        cmdTileMountainGround3,
        cmdTileMountainGround4,

        cmdTileMountBrickGround1,
        cmdTileMountBrickGround2,
        cmdTileMountBrickGround3,
        cmdTileMountBrickGround4,

        cmdTileRedBrickGround1,
        cmdTileRedBrickGround2,
        cmdTileRedBrickGround3,
        cmdTileRedBrickGround4,
        
        FurnishBox,
        FurnishBarrel,
        FurnishRat,
        FurnishRatRunning,
        FurnishSparrow,
        FurnishSparrowFlying,
        WebTile,
        //cmdBoardEdgeSideBright,
        //cmdBoardEdgeSideBrightLeft,
        //cmdBoardEdgeSideBrightRight,
        //cmdBoardEdgeSideDark,
        //cmdBoardEdgeSideDarkLeft,
        //cmdBoardEdgeSideDarkRight,
        //cmdBoardEdgeTop,
        //cmdBoardEdgeInside,

        cmdBridge,
        cmdBanner,
        cmdCheckOutlineEffect,
        cmdOrderCheckFlat,
       

        cmdMoveArrowMy,
        cmdMoveArrowDotMy,
        cmdMoveArrowAlly,
        cmdMoveArrowDotAlly,
        cmdMoveArrowLocked,
        cmdMoveArrowDotLocked,
        cmdMoveArrowStamina,
        cmdMoveArrowDotStamina,


        cmdOrderCheckOutline,
        cmdSelectionDotted,
        cmdSelectionFull,
        cmdInteractiveSquareFrame,
        cmdInteractiveSquareFrame_Attack,
        cmdActionTargetSeletion,
        toggTutorialArrow,
        cmdMapEntranceIcon,

        cmdHighlightedSquare,
        cmdArrowAttack,
        cmdCCAttack,
        
        cmdStatsMoveBox,
        cmdStatsMeleeBox,
        cmdStatsRangedBox,
        cmdStatsHealthBox,
        cmdStatsMove,
        cmdStatsMelee,
        cmdStatsRanged,
        cmdStatsRangedLength,
        cmdStatsHealth,

        cmdUnitCardSkillBg,
        //cmdStatsValueBg,
        cmdUnitCardRangeBg,
        cmdUnitCardArmorBg,
        cmdCardPortraitBoxLarge,
        cmdCardPortraitBoxSmall,
        cmdUnitCardNameBannerLeft,
        cmdUnitCardNameBannerMid,
        cmdUnitCardNameBannerRight,
        cmdUnitCardPropertyBox,
        toggPropertyTex,
        toggConditionPositiveTex,
        toggConditionNegativeTex,
        toggConditionNeutralTex,


        cmdDiceMelee,
        cmdDiceRanged,
        cmdDiceAttack,
        cmdDiceArmorLight,
        cmdDiceArmorHeavy,
        cmdDiceDodge,

        cmdArmorLight,
        cmdArmorHeavy,
        cmdArmorDodge,

        cmdMoveLengthHudIcon,
        cmdUnitMoveGui_Small,
        cmdUnitMeleeGui,
        cmdUnitRangedGui,
        cmdUnitLongRangedGui,
        cmdUnitMoveGui,
        cmdPetTargetGui,
        cmdUnitGuiArrow,
        cmdUnitGuiArrow_Enemy,
        cmdUnitMeleeGui_Small,
        cmdUnitRangedGui_Small,
        cmdUnitLongRangedGui_Small,
        //cmdUnitStatusGuiBar,
        cmdUnitStatusGui_Stamina,
        cmdUnitStatusGui_Health,
        cmdUnitStatusGui_StaminaBar,
        cmdUnitStatusGui_HealthBar,
        cmdUnitStatusGui_EmptyBar,

        cmdUnitMoveGui_EnemySmall,
        cmdUnitMeleeGui_EnemySmall,
        cmdUnitRangedGui_EnemySmall,
        cmdUnitLongRangedGui_EnemySmall,

        cmdAttackDirectionRed,
        cmdAttackDirectionWhite,
        cmdAttackDirectionRedArrow,
        BackStabArrow,
        BackStabIcon,
        
        cmdCoin,
        cmd1Honor,
        cmd2Honor,
        cmd3Honor,
        cmdWarningTriangle,

        cmdPointer,
        cmdPointerAttack,
        cmdClientPointer,
        defaultGamerIcon,

        cmdCard3by2,
        cmdCard5by1,
        cmdCard5by1Small,

        cmdStrategyBg,
        cmdStrategyOrder3,
        cmdStrategyDoubletime,
        cmdStrategyWideAdv,
        cmdStrategyCloseEncount,
        cmdStrategyDarkSky,
        cmdStrategyRush,

        hqStrategyMoveAttack,
        hqStrategyMoveMove,
        hqStrategyAttackAttack,
        hqStrategyRest,
        hqStrategyLineOfFire,
        hqStrategySwing3,
        hqStrategyAimedShot,
        hqStrategyPiercingShot,
        hqStrategyArrowRain,
        hqStrategyShieldWall,
        hqStrategyLootRun,
        hqStrategyPoisionBomb,
        hqStrategyStunBomb,
        hqStrategyHeroic,
        hqStrategyEarthShake,

        hqStrategyLeapAttack,
        hqStrategyTrapper,
        hqStrategyKnifeDance,

        cmdRetreatFlatSymbol,
        cmdHitFlatSymbol,
        cmdIcon2Hit,
        cmdIcon3Hit,
        cmdIconSpecial,
        cmdIconSurge,

        DoomSkull,
        DoomSkullGray,
        DoomClockIcon,
        DoomClockIconGray,

        DoomClockFace,
        DoomClockArm,

        DoomBanner,
        DoomBannerHighlight,
        DoomBarFrame,
        QuestBanner,
        QuestBannerHighlight,

        BronzeChestClosed,
        BronzeChestOpen,
        SilverChestClosed,
        SilverChestOpen,
        GoldChestClosed,
        GoldChestOpen,

        DamageSlashEffect1,
        DamageSlashEffect2,
        DamageSlashEffect3,
        DamageSlashEffect4,
        DamageSlashEffect5,
        DamageSlashEffect6,
        DamageSlashEffect7,


        cmdIconSurgeSmall,
        cmdIconBlockSmall,
        cmdIconHit1Small,

        cmdIconHourglassSmall,
        cmdIconStaminaSmall,
        cmdIconBloodrageSmall,
        cmdIconHourglassSmallGray,
        cmdIconStaminaSmallGray,
        cmdIconBloodrageSmallGray,

        toggDieTexAttackSide,
        toggDieTexAttackFront,
        toggDieTexMeleeAttackFront,
        toggDieTexRangeAttackFront,

        hqDieTexDefenceSide,
        hqDieTexDefenceDodgeFront,
        hqDieTexDefenceArmorFront,
        hqDieTexDefenceHeavyArmorFront,

        cmdDieTexAttackSide,
        



        hqDieTexSide,
        hqDieTexCritiqualHit,
        hqDieTexHit1,
        hqDieTexHit2,
        hqDieTexHit3,
        hqDieTexSurge1,
        hqDieTexSurge2,
        hqDieTexBlock1,
        hqDieTexBlock2,
        hqDieTexDodge,
        hqDieTexDodgeRanged,
        hqDieTexDodgeLongRange,
        hqDieTexMiss,

        cmdDieTexSide,
        cmdDieTexRetreat,
        cmdDieTexHit,
        cmdDieTexMiss,

        cmdSupporterIcon1,
        cmdSupporterIcon2,

        //cmdIconSupport_1,
        //cmdIconSupport_2,
        cmdRangedIcon,
        cmdCCIcon,
        cmdIconFollowUp,
        cmdIconTimeOut,
        cmdIconBackstab,
        cmdSpyglass,
        cmdSpyglassHighlighted,

        lineofsightEye,
        lineofsightEyeButton,
        lineofsightEyeButtonHighlighted,
        lineofsightEyeCenter,
        //defaultGamerIcon,

        cmdInfoBobble,
        cmdIconRank,
       // cmdIconNoController,
       // cmdUnitHeart,
        cmdMinusHeart,

        cmdHeartGrayed,
        cmdStaminaGrayed,
        cmdBloodrageGrayed,

        cmdHeartValueBox,
        cmdStaminaValueBox,
        cmdBloodrageValueBox,


        cmdShieldP1,
        cmdShieldP2,
        cmdStamina,
        cmdBloodRage,
        cmdArmorResult,

        cmdArmor2Result,
        
        cmdDiceIcon,
        cmdPierce,
        cmdConvertArrow,

        cmdAttackTerrain,
        cmdRemoveTrap,
        cmdLootAction,
        cmdThrowBombAction,

        cmdBattleHistoryButton,
        cmdPhaseCirkle,
        cmdIgnoreRetreat,
        cmdNoDefence,

        cmdSlotMashineHit,
        cmdSlotMashineHitCritical,
        cmdSlotMashineRetreat,
        cmdSlotMashineMiss,

        equipHand1,
        equipHand2,
        equipArmor,
        equipTrinket,
        equipQuickbelt,
        cmdBackpack,
        cmdItemPouch,
        cmdAddToBackpack,

        cmdPotionHealth,
        cmdPotionStamina,
        
        cmdBerserkerAxe,
        cmdElfBow,
        cmdStartBow, 
        cmdStartSword,
        cmdKnightSword,
        cmdWhip,
        cmdStartDagger,
        cmdArcherDagger,
        cmdThiefDaggersTier1,
        cmdThiefDaggersTier2,
        cmdPosionousDarts,
        cmdSpear,
        cmdThrowKnife,
        cmdSmokeBomb,
        cmdProtectionRune,
        cmdWaterBottle,
        cmdPotionPheonix,
        cmdRoundShield,
        cmdLeatherArmor,
        cmdMailArmor,
        cmdElfArmor,
        cmdApple,

        cmdInactiveMonster,
        cmdGrapple,
        cmdImmobile,
        cmdMoveToSlot,
        cmdAttackUp,
        cmdAttackDown,
        cmdMoveUp,
        cmdMoveDown,
        cmdUndeadIcon,
        cmdMonsterCommander,
        cmdRegenrate,
        cmdRetaliate,
        cmdParry,
        cmdFlying,
        cmdFrenzy,
        cmdPush,
        cmdPull,
        cmdSwing,
        cmdDarkHeal,
        cmdPoisionIcon,
        cmdBleedIcon,
        cmdLootFinder, 
        cmdDeliveryService,
        cmdLootCollector,
        cmdHiddenIcon,
        cmdStaminaDrain,
        cmdWebbed,
        cmdPullLever,
        cmdLightAction,
        cmdLockMechanical,
        cmdLockRuneH,
        cmdLockRuneB,
        cmdLockRuneF,
        cmdLockRuneA,

        cmdKeyRuneH,
        cmdKeyRuneB,
        cmdKeyRuneF,
        cmdKeyRuneA,

        cmdNoMove,
        cmdDullWeapon,
        cmdThrowIcon,
        cmdDefencelessIcon,
        cmdAiBrain,
        cmdAiBrainObjective,
        cmdAiBrainObjectiveAlways,
        cmdSlipThrough,
        cmdBark,
        cmdCarryFood,
        cmdTarget2,
        cmdTarget3,


        cmdArrowPierce,
        cmdArrowRegular,
        cmdStunnIcon,
        cmdDodge,
        cmdDodgeRanged,
        cmdDodgeLongRanged,
        cmdStaminaStep,
        cmdAttackTargetMelee2,
        cmdAttackTargetRanged2,

        cmdSlotMashineFrame,
        //cmdWheelBlockIcon,
        //cmdWhiteTex,
        cmdIconButtonYes,
        cmdIconButtonNo,
        cmdIconButtonBack,
        cmdIconButtonBlank,
        cmdIconButtonNextPhase,
        cmdIconButtonNextPhaseGrayed,
        cmdIconButtonNextPlayer,
        cmdIconButtonNextPlayerGrayed,

        cmdIconButtonReadyCheckGray,
        cmdIconButtonReadyCheck,

        cmdHudSideLabelRed,
        cmdHudSideLabelBlue,
        cmdHudSideLabelLightBlue,

        cmdHudBorderThick,
        cmdHudBorderThickButton,
        cmdHudBorderThin,
        cmdHudBorderThinDark,
        cmdHudBorderTooltip,
        cmdHudTooltipArrow,
        cmdHudBorderButton,
        cmdHudBorderButtonGray,
        cmdHudOptionsOn,
        cmdHudOptionsOff,
        cmdHudCheckOn,
        cmdHudCheckOff,
        cmdHudCross,

        cmdHudBorderPopup,
        cmdHudBorderPopupButton,
        cmdHudPopupButton,

        unitEmoteSmile,
        unitEmoteAngry,
        unitEmoteSnore,
        unitEmoteCry,
        unitEmoteBitter,
        unitEmoteLaugh,
        unitEmoteWink,
        unitEmoteEvil,
        unitEmoteThumbUp,
        unitEmoteThumbDown,
        unitEmoteLove,
        unitEmoteQuestion,
        unitEmoteAlerted,

        speachBobbleTexture,
        speachBobbleArrow,

        speachBobbleYellow,
        speachBobbleRed,
        speachBobbleDarkRed,
        speachBobbleWhite,


        cmdLargePlainCheckOn,
        cmdLargePlainCheckOff,

        //cmdWhiteFlatCirkle,
        cmdCanAttackRangedIcon_Move,
        //cmdCanMoveIcon_Highlight,
        //cmdCanAttackIcon_Highlight,
        

        cmdUnitBallista,

        cmdUnitChariot,
        //cmdUnitGriffin,
        //cmdUnitUndead_Hero,
        cmdUnitUndead_Necromancer,
        //cmdUnitHuman_Magician,
        //cmdUnitElf_Hero,
        //cmdUnitUndead_Hero2,
        cmdUnitOrc_Hero,

        cmdUnitHuman_LightArcher,
        cmdUnitHuman_HeavyArcher,
        cmdUnitHuman_Scout,
        cmdUnitHuman_LightSpearman,
        cmdUnitHuman_Warrior,
        cmdUnitHuman_HeavySpearman,
        cmdUnitHuman_LightCavalry,
        cmdUnitHuman_HeavyCavalry,
        cmdUnitHuman_SwordCavalry,
        cmdUnitHuman_HeroCavalry,
        //cmdUnitHuman_Golem,

        cmdUnitUndead_LightArcher,
        cmdUnitUndead_HeavyArcher,
        cmdUnitUndead_LightInfantry,
        cmdUnitUndead_MedInfantry,
        cmdUnitUndead_Warrior,
        cmdUnitUndead_SpearBeast,
        cmdUnitUndead_HeavySwordBeast,

        //cmdUnitUndead_HeavyInfantry,
        cmdUnitUndead_LightCavalry,
        cmdUnitUndead_HeavyCavalry,
        //cmdUnitUndead_Dragon,

        cmdUnitElf_Scout,
        cmdUnitElf_Archer,
        cmdUnitElf_Faun,
        //cmdUnitElf_LightInfantry,
        cmdUnitElf_HeavyInfantry,
        cmdUnitElf_Warrior,
        cmdUnitElf_Ferry,
        cmdUnitElf_ScoutHorse,
        cmdUnitElf_LightCavalry,
        cmdUnitElf_HeavyCavalry,
        cmdUnitElf_Wardancer,
        //cmdUnitElf_Treeman,
        //cmdUnitElf_Hero1,
        //cmdUnitElf_Hero2,

        cmdUnitOrc_LightArcher,
        cmdUnitOrc_HeavyArcher,
        cmdUnitOrc_GoblinSoldier,
        //cmdUnitOrc_GoblinGuard,
        cmdUnitOrc_LightSwordsman,
        cmdUnitOrc_HeavySwordsman,
        cmdUnitOrc_LightWolfRider,
        cmdUnitOrc_HeavyWolfRider,
        //cmdUnitOrc_Troll,
        //cmdUnitOrc_Spider,
        cmdUnitOrc_Warrior,
        cmdUnitOrc_GoblinGuard,
        cmdGoblinRunner,
        cmdGuardDog,
        cmdOrcGuard,
        cmdCannonTroll,
        cmdGoblinKnight,
        cmdGoblinBloated,
        cmdGoblinFoodBoss,
        cmdRoyalGuardMelee,
        cmdRoyalGuardArcher,


        cmdUnitTent,
        cmdUnitBatteringRam,
        cmdUnitSupplyWagon,
        cmdUnitBoneDragon,
        //cmdUnitHiResTest,

        hqTrapDecoy,
        hqRougeTrap,
        hqDarkPriest,

        cmdUnitPracticeDummy,
        cmdUnitPracticeDummyArmor,
        cmdUnitUnknownDummy1,
        cmdUnitUnknownDummy2,
        cmdUnitUnknownDummy3,
        cmdUnitUnknownDummy4,

        cmdHero_Magician,
        cmdHero_Knight,
        cmdHero_Archer,
        hqHero_Dwarf,
        hqHero_Recruit_Sword,
        hqHero_Recruit_Bow,
        hqHero_Amazon,
        hqHero_Chibi,
        hqHero_PaladinF,
        hqHero_KhajaF,

        hqSpikeTrap,
        hqSpringTrap,
        hqSpringTrapReleased,
        hqCampFireOff,
        hqCampFireOn,
        hqFoodStorage,
        hqLeverBase,
        hqLeverCog,
        hqLeverStick,
        hqAlarmBell,
        hqTier1Treasure,
        hqTier1TreasureOpen,
        hqTier2Treasure,
        hqTier2TreasureOpen,
        hqTier3Treasure,
        hqTier3TreasureOpen,
        
        hqPetCat,
        hqPetDog,
        hqPetRat,
        hqPetRatBigSack,
        hqCyclops,
        hqNaga,
        hqNagaCommander,
        hqNagaBoss,
        hqOgre,
        hqBat,
        hqCaveSpider,
        hqFireLizard,
        hqRabidLizard,


        hqPetFluffYellow,
        hqSpikeDamageEffect,

        KillMarkSkullflower,
        KillMarkSwordNecklace,
        KillMarkGraveStone,
        KillMarkRose,

        hqBatteResultBobbleDamage,
        hqBatteResultBobbleShield,
        hqBatteResultBobblePierce,
        hqBatteResultBobbleBg,

        hqDoorHoleOutLine,
        hqDoorOutLine,
        hqRegularDoor,
        hqRegularDoorEdge,


        cmdTutVideo_Pointer,
        cmdTutVideo_PointerClick,
        cmdTutVideo_FriendUnit,
        cmdTutVideo_EnemyUnit,
        cmdTutVideo_BoardTile,

        hqTutorial1,
        hqTutorial2,
        hqTutorial3,

        #endregion


        cgDeck,
        cgHand,
        cgAttack,
        cgSacrificeForCards,
        cgSacrificeForMana,
        cgBaseMinionGreen,
        cgBaseMinionYellow,
        cgBaseMinionOrange,
        cgBaseMinionPurple,
        cgBaseMinionCyan,
        cgBaseMinionRed,
        cgAttackMinionGreen,
        cgAttackMinionYellow,
        cgAttackMinionBrown,
        cgAttackMinionPurple,
        cgAttackMinionBlue,
        cgAttackMinionRedBrown,

        cgCrocodile,
        cgGoblinScout,
        cgGoblinLineman,
        cgGoblinKing,
        cgFatBird2,
        cgFatBird,
        cgStatueBoss,
        cgBee,
        cgSkeletonBoss,
        cgSkeleton,
        cgZombie,
        cgHen,
        cgSpitBird,
        cgSheep,
        cgPitbull,
        cgPig,
        cgLizard,
        cgOrcArcher,
        cgOldHog,
        cgHorseWhite,
        cgHorseRed,
        cgHorseBrown,
        cgHog,
        cgHogBaby,
        cgHarpy,
        cgGoblinWolfrider,
        cgBat2,
        cgBat1,
        cgSlime,
        cgBigOrcBoss,
        cgFrog,
        cgGoblinBerserk,
        cgElfWardancer,
        cgElfKnight,
        cgElfArcher,
        cgOrcLineman,
        cgOrcKnight,
        cgOrcRider,
        cgZombieLeader,
        cgMummy,
        cgGhost,
        cgUnderConstruction,
        cgSpiderBot,
        cgTrollBoss,

        cgDamage,
        cgNoMovement,
        cgMove1,
        cgMove2,
        cgMove3,
        cgTargetAllOpponents,
        cgTargetRow,
        cgTargetCol,
        cgTargetAll,
        cgCastleIcon,
        cgCardFrontMinion,
        cgCardFrontScroll,
        cgCardBack,
        cgTurnOver,
        cgButtonHighlight,
        cgDiagonalForward,
        cgProjectileAll4Dir,
        cgProjectile,
        cgPlaceInFrontOf,
        cgCrosshairIcon,
        cgManaGlow,
        
        

        #region FailingBird

        birdGroundTex,
        birdSkyTex,
        birdPillar,

        birdCoinHidden,
        birdCoin1,
        birdCoin2,
        birdCoin3,
        birdCoin4,
        birdCoin5,
        birdCoin6,
        birdCoinValue5,
        birdCoinValue10,
        birdCoinValue20,
        pjCoinWings1,
        pjCoinWings2,
        pjCoinWings3,
        pjCoinWings4,


        pjGoldValue1,
        pjGoldValue2,
        pjGoldValue3,
        pjGoldValue4,
        pjGoldValue5,

        birdCoinParticleYellow,
        birdCoinParticleBlue,
        birdCoinParticleGreen,
        birdFlapParticle,
        birdBumpWave,
        birdBallTrace,
        birdBumpCount0,
        birdBumpCount1,
        birdBumpCount2,
        birdBumpCount3,


        birdCannonBall,
        birdCannonBallSmoke1,
        birdCannonBallSmoke2,
        //birdSpikeBall,
        birdSpikeBall,
        //birdSpikeBallFlash,
        birdFireball,
        birdFireballParticle,
        birdBackgroundHill,
        birdBackgroundBush,
        birdBackgroundHouse,
        birdBackgroundTree,
        birdBackgroundFlower,
        birdBackgroundTemple,
        birdBackgroundColumn,
        birdBackgroundColumnBroken,
        birdBackgroundHillWide,
        birdFlowerPot,
        birdFlowerHead1,
        birdFlowerHead2,

        birdP1WingUp,
        birdP1WingDown,
        birdP1Dead,
        birdP2WingUp,
        birdP2WingDown,
        birdP2Dead,
        birdP3WingUp,
        birdP3WingDown,
        birdP3Dead,
        birdP4WingUp,
        birdP4WingDown,
        birdP4Dead,

        pigP1WingUp,
        pigP1WingDown,
        pigP1Dead,
        pigP2WingUp,
        pigP2WingDown,
        pigP2Dead,
        pigP3WingUp,
        pigP3WingDown,
        pigP3Dead,
        pigP4WingUp,
        pigP4WingDown,
        pigP4Dead,

        pigVoidWingUp,
        pigVoidWingDown,
        pigVoidDead,
        pigVoidBacon,

        pigBlingWingUp,
        pigBlingWingDown,
        pigBlingDead,
        pigBlingGlasses,

        fishP1WingUp,
        fishP1WingDown,
        fishDead,
        fishP2WingUp,
        fishP2WingDown,
        fishP3WingUp,
        fishP3WingDown,
        fishP4WingUp,
        fishP4WingDown,

        fishP1Dead,
        fishP2Dead,
        fishP3Dead,
        fishP4Dead,


        fishBlingWingUp,
        fishBlingWingDown,
        fishBlingDead,
        fishBlingGlasses,
        fishBlingScale,

        sheepWhiteWingUp,
        sheepWhiteWingDown,
        sheepWhiteDead,
        sheepP2WingUp,
        sheepP2WingDown,
        sheepP2Dead,
        sheepPinkWingUp,
        sheepPinkWingDown,
        sheepPinkDead,
        sheepP4WingUp,
        sheepP4WingDown,
        sheepP4Dead,

        sheepRainbowWingUp,
        sheepRainbowWingDown,
        sheepRainbowDead,
        sheepRainbowFur,

        mrwWingUp,
        mrwWingDown,
        mrwWingDead,
        meatpie1,
        meatpie2,
        meatpie3,
        meatpie4,
        meatpie5,
        meatpie6,

        emptyAnimal,

        goatWingUp,
        goatWingDown,
        goatDead,
        goatFur,

        pugWingUp,
        pugWingDown,
        pugDead,

        pugVoidWingUp,
        pugVoidWingDown,
        pugVoidDead,
        dogBoneVoid,

        dogBrownWingUp,
        dogBrownWingDown,
        dogBrownDead,
        dogBone,

        cowSpottyWingUp,
        cowSpottyWingDown,
        cowSpottyDead,
        cowSpottySkin,

        cowBrownWingUp,
        cowBrownWingDown,
        cowBrownDead,
        cowBrownSkin,
        cowMeat,

        hamsterOrangeWingUp,
        hamsterOrangeWingDown,
        hamsterOrangeDead,
        hamsterOrangeFur,

        hamsterPinkWingUp,
        hamsterPinkWingDown,
        hamsterPinkDead,
        hamsterPinkFur,

        catRedWingUp,
        catRedWingDown,
        catRedDead,
        catRedAngel,

        catBlueWingUp,
        catBlueWingDown,
        catBlueDead,
        catBlueAngel,

        catRainbowWingUp,
        catRainbowWingDown,
        catRainbowDead,
        catRainbowAngel,

        birdZombWingUp,
        birdZombWingDown,
        birdZombDead,

        pigZombWingUp,
        pigZombWingDown,
        pigZombDead,
        
        sheepZombWingUp,
        sheepZombWingDown,
        sheepZombDead,

        fishZombWingUp,
        fishZombWingDown,
        fishZombDead,

        sheepFurZomb,
        fishBoneZomb,
        pigBaconZomb,
        birdFeatherZomb,
        
         
        birdCloudFat,
        birdCloudFatWide,

        birdFeather1,
        birdFeather2,
        birdFeather3,
        birdFeather4,

        pigBacon,

        fishScale1,
        fishScale2,
        fishScale3,
        fishScale4,

        sheepFurWhite,
        sheepFur2,
        sheepFurPink,
        sheepFur4,



        birdTear,
        birdCloudSlim,
        birdCloudSlimWide,

        birdPayWallTex,
        birdEndWallTex,
        birdGameOver,
        birdNewHighScore,
        birdP2,
        birdPressStart,
        birdTapToFlap,
        birdBack,

        birdPlayerNumberIcon,
        birdButtonA,
        birdButtonB,
        birdButtonX,
        birdButtonY,
        birdButtonStart,
        birdStartText,

        birdDpadLR,
        birdUserHand,
        birdButtonPressUp,
        birdButtonPressDown,
        birdControllerIcon,

        birdChangeDirBox,
        birdEdgeArrows,
        birdHeart, birdHeartEmpty,
        birdLock,
        birdUnLock,


        birdSpeedUp,
        birdQuestionBox,
        birdLaserGun,
        birdShellShield,
        pjBarrel,
        birdPlayerCount,
        joustJumpUpShield,
        joustFallBoost,
        joustDiveBombFire,
        joustAirTrickWave,
        pjRoundFireParticle1,
        pjRoundFireParticle2,
        pjRoundFireParticle3,


        birdButtonAandLB,
        birdButtonYandRB,

        birdToasty,
        birdWolfScare,
        //birdJoustWinner,
        //birdJoustDraw,
        //birdJoustTimesUp,

        birdWhiteSoftBox,
        birdBobbleArrow,
        birdLobbyStartButton,
        birdLobbyMenuButton,
        birdLobbyReturnButton,
        birdLobbyExitButton,
        birdShopButton,
        pauseSymbol,
        birdNetworkIcon,
        birdNoNetwork,
        birdFriendsNetwork,
        birdAnyoneNetwork,

        pjButtonTexBlue,
        pjButtonTexRed,
        pjOptionButtonTexOn,
        pjOptionButtonTexOff,
        pjPlayIcon,
        pjForwardIcon,
        pjMenuIcon,
        pjTitleText,

        birdLobbyVisibilityAnyone,
        birdLobbyVisibilityFriends,
        birdLobbyVisibilityHidden,

        //birdOptionsButtonUnselected,
        //birdOptionsButtonSelected,
        birdJoinNetwork,
        birdZeroLobbies,
        birdFriendlyLobbyIcon,
        birdUnknownLobbyIcon,
        birdModeJoust,
        birdModeBagatelle,

        birdModeCarBall,
        birdModeMatch3,
        birdModeGolf,

        birdModeContruction,
        birdModeNextButton,
        birdUnlockModeDlc,
        birdUnlockModeDlcArrow,

        birdLocalPlayersCountIcon,
        birdOnlinePlayersCountIcon,


        hatBlingCap,
        hatHigh,
        hatViking,
        hatFez,
        hatPirate,
        hatCowboy,
        hatIndian,
        hatVlc,
        hatHalo,
        hatRobinHood,
        hatChidCap1,
        hatChidCap2,
        hatChidCap3,
        hatEnglish,
        hatGooglieEyes,
        hatSkyMask,
        hatBow,
        hatBunny,
        hatRainbow,
        hatKing,
        hatPrincess,
        hatRiddler,
        hatShades,
        hatButterix,
        hatScottish,
        hatLoveEyes,
        hatFrank,
        hatUniHorn,

        voidParticle1,
        voidParticle2,
        voidParticle3,

        rainbowParticle1,
        rainbowParticle2,
        rainbowParticle3,
        rainbowParticle4,
        rainbowParticle5,
        rainbowParticle6,

        blingParticle1,
        blingParticle2,
        blingParticle3,

        winnerParticle,

        birdPlayerFrame,
        birdPlayerFrameBling,
        birdPlayerFrameRainbow,
        birdPlayerFrameVoid,
        birdPlayerFrameZomb,
        birdPlayerFrameClose,
        birdTeam1Frame,
        birdTeam2Frame,


        pjNum0,
        pjNum1,
        pjNum2,
        pjNum3,
        pjNum4,
        pjNum5,
        pjNum6,
        pjNum7,
        pjNum8,
        pjNum9,
        pjNumPlus,
        pjNumMinus,
        pjNumMultiply,
        pjNumEquals,
        pjNumArrowR,
        pjNumExpression,
        pjNumQuestion,



        Dlc1True,
        Dlc1False,
        Dlc2True,
        Dlc2False,
        DlcZombie,

        DlcBoxPrime,
        DlcBoxBling,
        DlcBoxZombie,
        DlcBoxPrimeLarge,


        BirdTimesUp1, BirdTimesUp2,
        BirdThrophy,
        BirdNoThrophy,
        BirdRoundFlag,
        BirdShieldIcon,

        easterShell, easterShellTop, easterShellBottom,
        easterChick1, easterChick2,

        //TutorialBgTex,
        BlueprintBg,
        BluePrintSquareHalf,
        BluePrintSquareFull,
        PjJumpCurve,
        PjHeartFull,
        PjHeartBroken,
        PjDeathSpeechBobble,
        PjSmackIcon,
        PjHoldButtonBar,

        birdRotatingCrown1,
        birdRotatingCrown2,
        birdRotatingCrown3,
        birdRotatingCrown4,
        birdRotatingCrown5,
        birdRotatingCrown6,

        CountDownNumber1,
        CountDownNumber2,
        CountDownNumber3,

        bagBallExitFire1,
        bagBallExitFire2,
        bagBallExitFire3,
        bagBallExitFire4,
        bagBallExitFire5,
        bagBallExitFire6,
        bagBallExitFireParticleA1,
        bagBallExitFireParticleA2,  
        bagBallExitFireParticleA3,
        bagBallExitFireParticleB1,
        bagBallExitFireParticleB2,
        bagBallExitFireParticleB3,
        bagBallExitFireParticleC1,
        bagBallExitFireParticleC2,
        bagBallExitFireParticleC3,

        bagPeg1_off,
        bagPeg1_on,
        bagPeg2_off,
        bagPeg2_on,
        bagPeg3_off,
        bagPeg3_on,
        bagPeg4_off,
        bagPeg4_on,
        bagPeg5_off,
        bagPeg5_on,

        bagSnakePeg1_off,
        bagSnakePeg1_on,
        bagSnakePeg2_off,
        bagSnakePeg2_on,
        bagSnakePeg3_off,
        bagSnakePeg3_on,
        bagSnakePeg4_off,
        bagSnakePeg4_on,
        bagSnakePeg5_off,
        bagSnakePeg5_on,

        bagCoinPeg_off,
        bagCoinPeg_on,

        bagPegFlashAnim1,
        bagPegFlashAnim2,
        bagPegFlashAnim3,
        bagPegFlashAnim4,
        bagPegFlashAnim5,
        bagPegFlashAnim6,
        //bagPegFlashAnim7,

        bagSnakeHead,
        bagBumpRefill,
        bagSplitPickupEffect,

        bagCannon,
        bagRails,


        cballCarBlue,
        cballCarBlueTurnL,
        cballCarBlueTurnR,
        cballCarRed,
        cballCarRedTurnL,
        cballCarRedTurnR,
        cballCarOutline,
        cballCarTurnArrow,
        cballGoliePaddleBlue,
        cballGoliePaddleRed,

        cballTrack1,
        cballTrack2,
        cballTrack3,
        cballTrack4,
        cballTrack5,
        cballTrack6,
        cballTrack7,
        cballTrack8,

        cballBall,
        cballBallLarge,
        cballBallAnim1,
        cballBallAnim2,
        cballBallAnim3,
        cballBallAnim4,
        cballBallAnim5,
        cballBallAnim6,
        cballBallAnim7,
        cballBallAnim8,

        cballHat1,
        cballHat2,
        cballHat3,
        cballHat4,
        cballHat5,
        cballHat6,
        cballHat7,

        cballPigPinkHead,
        cballPigPinkHeadBlink,
        cballPigPinkArms,
        cballPigPinkArmsL,
        cballPigPinkArmsR,

        cballPigOrangeHead,
        cballPigOrangeHeadBlink,
        cballPigOrangeArms,
        cballPigOrangeArmsL,
        cballPigOrangeArmsR,

        cballSheepWhiteHead,
        cballSheepWhiteHeadBlink,
        cballSheepWhiteArms,
        cballSheepWhiteArmsL,
        cballSheepWhiteArmsR,

        cballSheepBlackHead,
        cballSheepBlackHeadBlink,
        cballSheepBlackArms,
        cballSheepBlackArmsL,
        cballSheepBlackArmsR,

        cballFishGreenHead,
        cballFishGreenHeadBlink,
        cballFishGreenArms,
        cballFishGreenArmsL,
        cballFishGreenArmsR,

        cballFishOrangeHead,
        cballFishOrangeHeadBlink,
        cballFishOrangeArms,
        cballFishOrangeArmsL,
        cballFishOrangeArmsR,

        cballBirdYellowHead,
        cballBirdYellowHeadBlink,
        cballBirdYellowArms,
        cballBirdYellowArmsL,
        cballBirdYellowArmsR,

        cballBirdPinkHead,
        cballBirdPinkHeadBlink,
        cballBirdPinkArms,
        cballBirdPinkArmsL,
        cballBirdPinkArmsR,

        cballEdgeTexture,
        cballGoalBlue,
        cballGoalRed,
        cballScoreOutline,
        cballScoreFilled,
        cballGloveBlue,
        cballGloveRed,


        golfArrowMark,
        golfArrowMarkWide,
        golfArrow1,
        golfArrow2,
        golfArrow3,
        golfArrow4,
        golfArrow5,
        golfArrow6,
        golfArrow7,
        golfArrow8,
        golfArrow9,
        golfArrow10,

        golfBrickBrown,
        golfBrickBlue,
        golfSpikeSquare,
        golfHole,

        golfSand1Bg,
        golfSand1Top,
        golfSand2Bg,
        golfSand2Top,

        golfGraySand1Bg,
        golfGraySand1Top,
        golfGraySand2Bg,
        golfGraySand2Top,

        golfGrassGreen,
        golfGrassBlue,
        golfGrassRed,
        golfGrassYellow,
        golfGrassGray,

        golfChickenFlag,
        golfChickenFlagFeather,
        golfStunnStars,
        golfBomb,
        golfBombRed,

        golfBugWalkS1,
        golfBugWalkS2,
        golfBugWalkN1,
        golfBugWalkN2,
        golfBugHideS1,
        golfBugHideS2,
        golfBugHideN1,
        golfBugHideN2,
        golfBugDead,

        m3BrickYellow,
        m3BrickRed,
        m3BrickOrange,
        m3BrickPurple,
        m3BrickBlue,
        m3BrickGreen,
        m3BrickStone,

        m3PrevBrickYellow,
        m3PrevBrickRed,
        m3PrevBrickOrange,
        m3PrevBrickPurple,
        m3PrevBrickBlue,
        m3PrevBrickGreen,

        m3GrayBrickYellow,
        m3GrayBrickRed,
        m3GrayBrickOrange,
        m3GrayBrickPurple,
        m3GrayBrickBlue,
        m3GrayBrickGreen,
        m3GrayBrickStone,

        m3RotateArrow,
        m3GameSpeedArrow,
        m3GameSpeedArrowGray,

        cirkleThick1Diameter26,

        mobaHenBlue,
        mobaHenRed,
        mobaNinjaStarBlue,
        mobaNinjaStarRed,

        mobaPigBlue,
        mobaPigRed,
        mobaGoatBlue,
        mobaGoatRed,
        mobaCatBlue,
        mobaCatRed,
        modaTowerBlue,
        mobaTowerRed,

        spaceWarAstreoidRedLarge,
        spaceWarAstreoidBlueLarge,
        spaceWarAstreoidRed,
        spaceWarAstreoidBlue,

        spaceWarAstreoidParticleRed1,
        spaceWarAstreoidParticleRed2,
        spaceWarAstreoidParticleRed3,
        spaceWarAstreoidParticleRed4,
        spaceWarAstreoidParticleRed5,
        spaceWarAstreoidParticleRed6,
        spaceWarAstreoidParticleBlue1,
        spaceWarAstreoidParticleBlue2,
        spaceWarAstreoidParticleBlue3,
        spaceWarAstreoidParticleBlue4,
        spaceWarAstreoidParticleBlue5,
        spaceWarAstreoidParticleBlue6,

        //spaceWarTurnArrowPointing,
        spaceWarTurnArrow,
        spaceWarTurnArrowOnShield,

        spaceWarShipYellow,
        spaceWarShipYellowTailMid,
        spaceWarShipYellowTailEnd,
        spaceWarShipShield,
        spaceWarShipTailShield,
        
        spaceWarRocket1,
        spaceWarRocket2,
        spaceWarLorry,
        spaceWarPolice1,
        spaceWarPolice2,

        spaceWarShopSquareOn,
        spaceWarShopSquareOff,
        spaceWarShopAddTail,


        spaceWarFogLine1,
        spaceWarFogLine2,
        spaceWarFogLine3,
        spaceWarFogLine4,
        spaceWarFogCirkle1,
        spaceWarFogCirkle2,
        spaceWarFogCirkle3,
        spaceWarFogCirkle4,
        spaceWarFogCirkle5,
        spaceWarFogCirkle6,
        spaceWarFogCirkle7,
        spaceWarFogCirkle8,
        spaceWarFogCirkle9,
        spaceWarFogCirkle10,
        spaceWarFogCirkle11,
        spaceWarStarWhite,

        spaceWarRocketFire,
        spaceWarRocketFireWide,
        spaceWarCargoIcon,
        Ticket,
        //AdButtonLootfest,
        //AdButtonDwelvers,

        MenuIconExit,
        MenuIconResume,
        MenuIconMusicVol,
        MenuIconSoundVol,
        MenuPixelIconMusicVol,
        MenuPixelIconSoundVol,
        MenuIconCredits,
        MenuIconSettings,
        //MenuIconFullScreen,
        MenuPixelIconSettings,
        MenuPixelIconManual,
        MenuPixelIconPlay,

        MenuIconScreenResolution,
        MenuIconMultiMonitor,
        MenuIconApplyResolution,

        MenuIconMonitorFrame,
        MenuIconMonitorArrowsOut,
        MenuIconMonitorArrowsIn,

        
        MousePointer,
        ClickCirkleEffect,

        LittleUnitIconTower,
        LittleUnitIconVikingman,
        LittleUnitIconSpearman,
        LittleUnitIconSoldierMan,
        LittleUnitIconSlingman,
        LittleUnitIconHealerMan,
        LittleUnitIconDogman,
        LittleUnitIconFatman,
        LittleUnitIconArcherman,
        LittleUnitIconScoutman,
        LittleUnitIconFarmerman,
        LittleUnitIconFarmerHordeman,
        LittleUnitIconBallistaman,
        LittleUnitIconKnightman,
        LittleUnitIconCrossBowman,
        LittleUnitIconRocketLauncherman,
        LittleUnitIconBombThrowerman,
        LittleUnitIconRamMan,
        LittleUnitIconLongSwordMan,
        LittleUnitIconJavelinerMan,
        LittleUnitIconKingMan,
        LittleUnitIconMillMan,
        LittleUnitIconBannerMan,

        LittleHaltOrder,
        LittleMoveOrder,
        LittleUnitShadow,
        LittleFlagIconNeutral,
        LittleFlagIconMan,
        LittleFlagIconOrc,
        LittleMinusCoin,
        LittleMoveArrowFilled,
        LittleMoveArrowOutline,
        LittleUnitSelectionFilled,
        LittleUnitSelectionDotted,
        LittleThumbBobble,

        LittleStatsUnitTarget,
        LittleStatsUnitTargetArrow,

        LittleStatsSoldiersCount,
        LittleStatsAddPig,
        LittleStatsScoutMovement,
        LittleThumbUp,
        LittleThumbDown,

        LittleStatsNotStructure,
        LittleStatsProjectileAttack,
        LittleStatsAttack,
        LittleStatsStructure,
        //LittleStatsLength,
        LittleStatsRange,
        LittleStatsMoveArrows,
        LittleStatsMoveShoe,
        LittleStatsDamage,
        LittleStatsTime,
        LittleStatsHealth,

        LittleStatsProjectileArmor,
        LittleStatsNotSoldier,
        LittleStatsBomb,
        LittleStatsBombRadius,
        LittleStatsTargetStructure,
        LittleStatsBanner,

        LittleCardBgMan,

        warsSceneBg,
        warsTitle,
        warsMapSettings,
        warsDefaultPlayerIcon,
        #endregion

        #region DSS WARS
        WarsNightmareEyeGlow,
        WarsGroundTex,
        warsFoliageShadow,
        warsWorkerPromoHammer,
        warsWorkerPromoBox,


        WarsRelationAlly,
        WarsRelationGood,
        WarsRelationPeace,
        WarsRelationNeutral,
        WarsRelationTruce,
        WarsRelationWar,
        WarsRelationTotalWar,
        WarsRelationFlagOutline,
        WarsRelationFlag,

        WarsStrengthIcon,
        WarsGroupIcon,
        WarsSoldierIcon,

        WarsCommandPoint,
        WarsCommandAdd,
        WarsCommandAddTime,
        WarsCommandSub,
        WarsCommandSubTime,
        WarsDiplomaticPoint,
        WarsDiplomaticAdd,
        WarsDiplomaticAddTime,
        WarsDiplomaticSub,
        WarsDiplomaticSubTime,

        WarsGuard,
        WarsGuardAdd,
        WarsWorker,
        WarsWorkerAdd,
        WarsWorkerSub,

        WarsDarkLordBossIcon,
        WarsFactoryIcon,

        WarsUnitIcon_Soldier,
        WarsUnitIcon_TwoHand,
        WarsUnitIcon_Archer,
        WarsUnitIcon_Ballista,
        WarsUnitIcon_Knight,
        WarsUnitIcon_Honorguard,
        WarsUnitIcon_Pikeman,
        WarsUnitIcon_Trollcannon,
        WarsUnitIcon_Viking,
        WarsUnitIcon_Greensoldier,
        WarsUnitIcon_Folkman,

        WarsBuild_WorkerHuts,
        WarsBuild_Postal,
        WarsBuild_Recruitment,
        WarsBuild_Barracks,
        WarsBuild_Tavern,
        WarsBuild_Brewery,
        WarsBuild_Cook,
        WarsBuild_Smith,
        WarsBuild_WheatFarms,
        WarsBuild_LinenFarms,
        WarsBuild_PigPen,
        WarsBuild_HenPen,
        WarsBuild_Statue,
        WarsBuild_Carpenter,
        WarsBuild_Nobelhouse,
        WarsBuild_WorkBench,
        WarsBuild_CoalPit,
        WarsBuild_Pavement,
        WarsBuild_PavementFlowers,

        WarsResource_LightArmor,
        WarsResource_MediumArmor,
        WarsResource_HeavyArmor,
        WarsResource_Sharpstick,
        WarsResource_Sword,
        WarsResource_Bow,
        WarsResource_Ballista,
        WarsResource_Beer,
        WarsResource_Iron,
        WarsResource_IronOre,
        WarsResource_GoldOre,
        WarsResource_RawFood,
        WarsResource_Food,
        WarsResource_Wood,
        WarsResource_Fuel,
        WarsResource_Wheat,
        WarsResource_Linen,
        WarsResource_Egg,
        WarsResource_RawMeat,
        WarsResource_Stone,
        WarsResource_Water,
        WarsResource_WaterAdd,        
        WarsResource_SkinAndLinen,
        WarsResource_TwoHandSword,
        WarsResource_KnightsLance,
        WarsResource_LinenCloth,

        WarsHome,
        WarsDelivery,
        WarsTrade,
        WarsBluePrint,
        WarsStockpileAdd,
        WarsStockpileStop,


        #endregion

        #region RTS
        rtsSpearmen,
        rtsCavalry,
        rtsBallista,
        rtsSeaWarrior,
        rtsBattleXpMeter,
        rtsFatigueMeter,
        rtsBattleIcon,
        rtsArmyBanner,
        rtsBorderDot,
        rtsCirkleLoadingBar,
       // rtsApBarTex,

        //rtsBlockSide,
        //rtsBlockTop,
        //rtsBBTree,
        //rtsBBStone,

        
        rtsSelection1,
        rtsSelection2,
        //rtsSelectionButton,
        rtsIncome,
        rtsIncomeSum,
        rtsUpkeep,
        rtsMoney,
        rtsHonor,
        rtsAPbar,
        rtsIncomeTime,
        rtsUpkeepTime,

        //rtsSoldierCount,
        // rtsCityIconFill,
        // rtsArmyIconFill,
        //rtsCityIcon,
        //rtsArmyIcon,
        rtsBattleHistory,
        rtsWarningPopBG,
        rtsWarningPopBgArrow,
        rtsWarningPopReady,
        rtsWarningPopExpression,
        rtsHomeIcon,
        rtsShipRemove,
        rtsShipBuild,
        rtsShip,

        rtsAIFlaySymbol,
        //rtsFlagTextureBase,

        rtsAllianceIcon,
        rtsRelationNeurtal,
        rtsRelationAllied,
        rtsRelationAtWar,
        rtsRelationNemesis,

        rtsLoading0of8,
        rtsLoading1of8,
        rtsLoading2of8,
        rtsLoading3of8,
        rtsLoading4of8,
        rtsLoading5of8,
        rtsLoading6of8,
        rtsLoading7of8,
        rtsLoading8of8,

        rtsFactionFlagIcon,

        rtsAnalyzeBattle,
        rtsSplitArmy,
        rtsCombineArmies,
        rtsDisbandArmy,

        rtsSmallCityProfileIcon,
        rtsLargeCityProfileIcon,
        rtsHeadCityProfileIcon,
        rtsPlayCommanderButton,

        #if RTS
        rtsFactionFlagTexureStart,
        rtsFactionFlagTexureEnd = rtsFactionFlagTexureStart + VikingEngine.DSSWars.DssLib.RtsMaxFactions,
        #endif
        rtsApDotFull,
        rtsApDotHalf,
        rtsApDotEmpty,
        rtsCityLink,
        rtsArmyLink,

        rtsCardBg,
        //rtsFactionCityIconStart,
        //rtsFactionCityIconEnd = rtsFactionCityIconStart + RTS.RTSlib.MaxFactions,

        //rtsFactionArmyIconStart,
        //rtsFactionArmyIconEnd = rtsFactionArmyIconStart + RTS.RTSlib.MaxFactions, 

        #endregion

        NUM
    }


}

