<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType Condition="'$(Configuration)' == 'Debug'">Exe</OutputType>
    <OutputType Condition="'$(Configuration)' != 'Debug'">WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <PlatformTarget>x64</PlatformTarget>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
    <MonoGamePlatform>DesktopVK</MonoGamePlatform>
    <AssemblyName>VikingEngine</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\Vikingengine\Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <!--<ItemGroup>
    <None Remove="Icon.ico" />
    <None Remove="Icon.bmp" />
  </ItemGroup>-->
  <ItemGroup>
    <EmbeddedResource Include="..\Vikingengine\Icon.ico">
      <LogicalName>Icon.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Vikingengine\Icon.bmp">
      <LogicalName>Icon.bmp</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.6-preview.*" />
    <PackageReference Include="MonoGame.Runtime.Windows.Vulkan" Version="3.8.6-preview.*" />
    <PackageReference Include="MonoGame.Runtime.Mac.Vulkan" Version="3.8.6-preview.*" />
    <PackageReference Include="MonoGame.Runtime.Linux.Vulkan" Version="3.8.6-preview.*" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.6-preview.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Steamworks repo\Steamworks.NET\Standalone2.0\Steamworks.NET.Standard.csproj">
      <SetConfiguration Condition="'$(Configuration)' != 'Release'">Configuration=Windows</SetConfiguration>
      <SetPlatform>Platform=x64</SetPlatform>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VikingEngine\VikingEngine.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="steam_api64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="..\VikingBuilder\BuildContent.targets" />
</Project>