using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace VikingEngine.LootFest.GO
{
    enum GameObjectType
    {
        Error = 0,
        CHARACTER_0,//-----------------
        Hero,
        WolfHero,
        BasicNPC,
        AmmoGranPa,
        Guard,
        Salesman,
        Dummie,
        Creature,
        FlyingPet,
        CritterPig,
        CritterHen,
        Chick,
        CritterSheep,
        CritterWhiteHen,
        FlyingPig,
        HappyNpc,
        HorseRidingHero,
        Horse,
        CritterMiningCow,
        CritterMiningPig,
        Miner,
        EmoSuitSmith,
        TrollTutorialGranpa,
        MinerSalesman,
        SuitGranpa,
        Mother,
        JumpTutFather,
        AttackTutGuard,
        CheckPointNpc,
        HorseTransport,
        ProgressNPC,

        MONSTER_1 = 100,//-----------------
        Crocodile,
        Ent,
        FireGoblin,
        Frog,
        Harpy,
        Hog,
        OldSwine,
        Lizard,
        Scorpion,
        Spider,
        Wolf,
        Squig,
        SquigSpawn,
        FatBird,
        Ogre,
        Humanioid,
        Grunt,
        Magician,
        Mummy,
        Moth,
        Ghost,
        Fly,
        Bat,
        GreenSlime,
        ShootingTurret,
        TrapRotating,
        TrapBackNforward,
        EndBossMount,
        EvilSpider,
        Bee,
        GoblinSpiderRiderMiniBoss,
        Zombie,
        Skeleton,
        ZombieLeader,
        BabyZombie,
        DogZombie,
        FatZombie,
        GoblinScout, GoblinLineman, GoblinBerserk,
        OrcSoldier,
        OrcArcher,
        OrcBrute,
        OrcKnight,
        GreatWolf,
        StatueBoss,
        BigOrcBoss,
        SpitChick,
        Pitbull,
        GoblinKing,
        MidOrcBoss,
        ElfArcher,
        ElfWardancer,
        ElfKnight,
        HogBaby,

        MiniSpider,
        PoisionSpider,
        BullSpider,
        SpiderBot,
        SpiderBoss,
        ElfKing,
        Beetle1,
        SquigRed, SquigRedBaby,
        SquigGreen, SquigGreenBaby,
        SquigHorned, SquigHornedBaby,
        ScorpionBot,
        MinerSpider,
        TrollBoss,
        
        //48
        WEAPONATTACK_2 = 200,//-----------------
        PlayerShield,
        Impulse,
        GravityArrow,
        GoldenArrow,
        SlingStone,
        BabyAxe,
        SkeletonBone,
        Javelin,
        ShapeShifterJavelin,
        GoblinJavelin,
        BotRocket,
        ToyBoatProjectile,
        FlyingPetProjectile,
        ProjectileEvilBurst,
        ProjectilePoisionBurst,
        Bomb,
        ExplodingBarrel,
        EvilMissile,
        TurretBullet,
        SquigBullet,
        ScorpionBullet1,
        ScorpionBullet2,
        EntRoot,

        FireGoblinBall,
        GruntStone,
        SquigSpawnBullet,
        OrcArrow,
        BombLightSpark,
        MagicianLightSpark,
        MagicianPoisonBomb,
        MagicianThrowSword,
        MagicianFireball,
        FireBreath,
        Explosion,

        NecroBall,
        NecroMetroite,
        WiseLadyAttack,
        FatEgg,
        BatSonar,
        Mushroom,
        SpitChickBullet,

        MashineGunBullet,
        SideArmBullet,
        HandGranade,

        BasicSuitAttack,
        SwordsManAttack,
        ArcherAttack,
        DaneAttack,
        DualAxeAttack,
        SpearManAttack,
        ShapeShifterAttack,

        GoblinBoneAttack,
        GoblinLinemanSpearAttack,
        OrcSoldierSwordAttack,
        OrcKnightAttack,
        OrcArcherSwordAttack,
        BigOrcBossAttack,

        NpcAttack,
        CardThrow,
        ThrowAxe,
        ElfSword,
        ElfLongSword,
        ElfArrow,
        LargeSkeletonBone,
        SpiderWeb,
        PoisionSpiderProjectile,
        PickAxe,

        ENVIRONMENT_3 = 300,//-----------------
        BloodFingerHerb,
        FrogHeartHerb,
        FireStarHerb,
        BlueRoseHerb,
        MiningSpot,
        BeeHive,
        HitTarget,
        EggNest,
        GoblinSpawner,
        OrcSpawner,
        TerrainDamageArea,
        TerrainBuildArea,
        GoldChest,

        ELEMENT_4 = 400,//-----------------
        Fire,
        Thunder,

        INTERACT_5 = 500,//-----------------
        SpeakDialogue,
        Chest,
        DiscardPile,
        Teleport,
        //Message,
        StationaryWeapon,
        Mining,
        Golf,
        Door,
        LootCrate,
        AreaLock,
        TeleportWithin,

        PICKUP_6 = 600,//-----------------
        Coin,
        FoodScrap,
        HealUp,
        MagicUp,
        SpecialAmmo1, SpecialAmmoFull,
        Key,
        ItemBox,
        SuitBox,
        ItemForSale,
        Baby,
        CardCapture,
        MiningMithril,

        EFFECT_7 = 700,//-----------------
        PreRangedAttackWeaponEffect,
        BossDeathExplosion,
        ExplodingBullSpider,
        NUM_NON
    }
}
